# Generated by Django 6.0.2 on 2026-03-02 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.categoria'),
        ),
    ]
